### ISSUE TITLE
New extensions for SMART

### ISSUE THREAD

**Issue by ghost** [Gradiant/smart-xapi-dsl#1]
Hi, it's Tatiana from Netex. I need to add two new extensions for xapi:

   activityMode: "https://w3id.org/xapi/smart/extension/result/activity-mode"
   activityStatus: "https://w3id.org/xapi/smart/extension/result/activity-status"

Thanks,

**Comment by josevilasw** [comment]
Closed in https://github.com/Gradiant/smart-xapi-dsl/commit/2f71708754500b3834c00b31d23806bfab9c1b6e
